version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mongo-to-postgres-migration"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-XXXXXXXXXXXX"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []