version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mongo-to-postgres-migration"
s3_bucket = "samclisourcebucket-123454"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []