AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Serverless MongoDB to PostgreSQL Data Migration

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID (default VPC)
    Default: vpc-03e0d958406d5cb79
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnet IDs for Lambda functions
    Default: subnet-03ee0d8610a751d07,subnet-07368c456ed3e8211
  PGHost:
    Type: String
    Description: PostgreSQL host endpoint

  PGUser:
    Type: String
    Description: PostgreSQL username

  PGPassword:
    Type: String
    Description: PostgreSQL password
    NoEcho: true

  PGDatabase:
    Type: String
    Description: PostgreSQL database name

  MongoURI:
    Type: String
    Description: MongoDB connection URI
    NoEcho: true

Globals:
  Function:
    Timeout: 900
    Runtime: python3.9
    MemorySize: 128
    VpcConfig:
      SecurityGroupIds:
        - !Ref LambdaSecurityGroup
      SubnetIds: !Ref SubnetIds
    Environment:
      Variables:
        LOG_LEVEL: INFO
        BATCH_SIZE: 1000

Resources:
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Lambda functions
      VpcId: !Ref VpcId
      SecurityGroupEgress:
        - IpProtocol: "-1"
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0

  MongoPythonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: mongo-python-layer
      Description: Dependencies for MongoDB and PostgreSQL functions
      ContentUri: layers/mongodb/
      CompatibleRuntimes:
        - python3.9
      RetentionPolicy: Retain

  ReadMongoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/read_mongo/
      Handler: app.lambda_handler
      Layers:
        - !Ref MongoPythonLayer
      Environment:
        Variables:
          MONGO_SECRETS_ARN: !Ref MongoDBSecrets
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref MongoDBSecrets

  TransformDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/transform_data/
      Handler: app.lambda_handler
      Layers:
        - !Ref MongoPythonLayer

  WritePostgresFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/write_postgres/
      Handler: app.lambda_handler
      Layers:
        - !Ref MongoPythonLayer
      Environment:
        Variables:
          POSTGRES_SECRETS_ARN: !Ref PostgresSecrets
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref PostgresSecrets

  MongoDBSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: MongoDB connection details
      SecretString: !Sub '{"uri": "${MongoURI}"}'

  PostgresSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: PostgreSQL connection details
      SecretString: !Sub '{"host": "${PGHost}", "username": "${PGUser}", "password": "${PGPassword}", "database": "${PGDatabase}"}'

  MigrationStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Definition:
        StartAt: ReadMongo
        States:
          ReadMongo:
            Type: Task
            Resource: !GetAtt ReadMongoFunction.Arn
            Next: TransformData
            ResultPath: "$"
            Retry:
              - ErrorEquals: ["MongoReadError", "States.TaskFailed"]
                IntervalSeconds: 3
                MaxAttempts: 3
                BackoffRate: 2
            Catch:
              - ErrorEquals: ["States.ALL"]
                Next: FailState
                ResultPath: "$.error"

          TransformData:
            Type: Task
            Resource: !GetAtt TransformDataFunction.Arn
            Next: WritePostgres
            ResultPath: "$"
            Retry:
              - ErrorEquals: ["TransformError", "States.TaskFailed"]
                IntervalSeconds: 3
                MaxAttempts: 3
                BackoffRate: 2
            Catch:
              - ErrorEquals: ["States.ALL"]
                Next: FailState
                ResultPath: "$.error"

          WritePostgres:
            Type: Task
            Resource: !GetAtt WritePostgresFunction.Arn
            Next: CheckMoreRecords
            ResultPath: "$"
            Retry:
              - ErrorEquals: ["States.TaskFailed"]
                IntervalSeconds: 3
                MaxAttempts: 3
                BackoffRate: 2
            Catch:
              - ErrorEquals: ["States.ALL"]
                Next: FailState
                ResultPath: "$.error"

          CheckMoreRecords:
            Type: Choice
            Choices:
              - Variable: "$.has_more"
                BooleanEquals: true
                Next: ReadMongo
            Default: SuccessState

          SuccessState:
            Type: Succeed

          FailState:
            Type: Fail
            Cause: "Migration Process Failed"
            Error: "MigrationError"

      Role: arn:aws:iam::600627337305:role/StateMachineExecutionRole
