name: Deploy SAM Application

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aws-sam-cli
          pip install pymongo psycopg2-binary

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build
        run: sam build

      - name: Deploy
        run: sam deploy \ 
            --no-confirm-changeset \ 
            --no-fail-on-empty-changeset \
            --stack-name mongo-to-postgres-migration \
            --s3-bucket samclisourcebucket-123454 \
            --parameter-overrides \
              "VpcId=vpc-03e0d958406d5cb79" \
              "SubnetIds=subnet-03ee0d8610a751d07,subnet-07368c456ed3e8211" \
              "MongoURI=${{ secrets.MONGO_URI }}" \
              "PGHost=${{ secrets.PG_HOST }}" \
              "PGUser=${{ secrets.PG_USER }}" \
              "PGPassword=${{ secrets.PG_PASSWORD }}" \
              "PGDatabase=${{ secrets.PG_DATABASE }}" \
            --capabilities CAPABILITY_IAM \
            --region "${{ secrets.AWS_REGION }}"